### ISSUE TITLE
Incorrect URL generated for theme preview image for third party themes

### ISSUE THREAD

**Issue by gRoberts84** [opencart/opencart#11886]
**What version of OpenCart are you reporting this for?**

4.0.1.1

**Describe the bug**

Setting/Setting::Theme incorrectly using `DIR_EXTENSION` instead of `HTTP_CATALOG` to reference the Theme preview image.

`$image = DIR_EXTENSION . $extension_info['extension'] . '/catalog/view/image/' . $extension_info['code'] . '.png';`

**To Reproduce**

- Install and activate a new theme.
- Go to System > Settings.
- Edit default store.
- Change theme from default to newly installed theme.

The above makes a request to `/admin/index.php?route=setting/setting|theme&user_token=***&theme=theme_name`, which for the default theme, it will return `http://domain.tld/catalog/view/image/basic.png` but for others, it will return `/local/path/to/opencart/extension/theme_name/catalog/view/image/theme_name.png`.

**Expected behavior**

Should return `http://domain.tld/extension/theme_name/catalog/view/image/theme_name.png`.

**Comment by danielkerr** [comment]
i think fixed in master branch already please test

**Comment by TheCartpenter** [comment]
URL shows a '|' character. The latest MB release uses a: '.' in the URL.

**Comment by gRoberts84** [comment]
https://github.com/opencart/opencart/blob/master/upload/admin/controller/setting/setting.php#L821

Still showing as using DIR_EXTENSION unfortunately.

**Comment by danielkerr** [comment]
ur right, fixing now.
