### ISSUE TITLE
Product with uploaded file as option cannot be added to the cart

### ISSUE THREAD

**Issue by stefankapp** [opencart/opencart#12060]
**What version of OpenCart are you reporting this for?**
OC4

**Describe the bug**
On the frontend, when uploading a file as a required product option, the product cannot be added to the cart.

**To Reproduce**
1. Go to https://demo.opencart.com/index.php?route=product/product&language=en-gb&path=25_28&product_id=42 and upload an empty txt file.
2. Choose the other options
3. Click on 'Add to Cart'
4. 'File required!' is shown

**Expected behavior**
After click on 'Add to Cart' the product including the uploaded file should be added to the cart.

**Screenshots / Screen recordings**
<img width="1040" alt="oc4-upload-error" src="https://user-images.githubusercontent.com/47218181/204690666-2b6840c7-8cc0-440f-afc4-179468014e6f.png">

**Server / Test environment (please complete the following information):**
 - demo.opencart.com (in OC3 it used to work)
 - Tested with Chrome, Edge

**Additional context**
In my local OC4, the files are uploaded to the storage/upload directory and in the db table oc_upload the information like upload_id, name, filename, etc. is added. However, same behavior as on the demo server, there seems to be an issue pushing the information to the customer's cart.

**Comment by pemaier** [comment]
No option and no attribute at all can be added

**Comment by mhcwebdesign** [comment]
The demo server uses an older (probably 4.0.0.0) version, which is not the same as the master branch. This particular issue with the file upload appears to be already resolved in the master branch (the upcoming 4.0.2.0 release).

@pemaier: Yours is a different issue, so please use or open a separate issue for this, providing more details.

**Comment by pemaier** [comment]
As I wrote the problem is still present... 
No option and no attribute at all can be added
I [just installed](https://nettwork.ru/opencart/master.demo/admin0) for you now to test (demo/demo) ... may you get other results)
