### ISSUE TITLE
  ocmod cannot handle renamed admin folder

### ISSUE THREAD

**Issue by TLEwebdevs** [opencart/opencart#2816]
As posted in OC forums - http://forum.opencart.com/viewtopic.php?f=191&t=142296

This is a bug report, I've found quick and dirty workarounds as detailed below - OC devs need to address the main issue reported ...

Main issues -

1. The install and configuration guide pages on the OpenCart site call for renaming the admin folder as a highly recommended action (I agree with that). However this breaks the modifications installer for ocmod extensions.

1a. If the ocmod extension contains a folder and file set for /admin/ in the upload folder, the main extensions installer does not redirect the upload to the renamed admin folder, instead it creates a new folder called admin and sends the upload there.

1b. The extensions installer does not recognise the renamed admin folder for actioning the install.ocmod.xml file and fails without errors leaving no addition of links and settings in admin for the uploaded extension - also no addition of the extension to Users - User Groups - for setting access and modification permissions.

There are some workarounds I have found through trial and error, but they are not a long term solution and they are certainly not recommended if OC is building towards a WordPress-style solution where modifications can be downloaded and installed direct from the OpenCart repository from within the modifications installer ...

2. Download the extension to your local hard drive and unzip it.
- rename the admin folder to your new name for admin (e.g. if your admin folder is called rottentomato then use the same name to rename the admin folder in the extension package.
- make sure the install.xml is called install.ocmod.xml (I have found too many 2.0.1.1 extensions without this)
- re-zip the package with its original name

2a. upload via the extensions installer and refresh the modifications cache
- first thing you will most probably notice is that EITHER the left menu link in admin does not display where it should be AND / OR the permissions checkboxes in Users-User Groups are missing.
- open the install.ocmod.xml file on your local hard drive ... now hard code the changes into the files and places on your server install that are indicated in the XML code.
- go back to the modifications list page in admin and refresh the modifications cache ... several times - it does not always "take" on the first attempt.
- go back to Users-Users Groups and look for the permissions checkboxes, they should be there now, tick them and save, then back to modifications to refresh the cache several times again.
- now look throughout the left hand admin menu for the settings page link - if it's not there, refresh the cache and if still not there, check again next week when it will mysteriously appear in some illogical position ... at least that's how I've experienced it.

Hope it helps someone, especially the OC Devs - take a look at how vqmod handles renaming the admin folder - ocmod needs something similar.

**Comment by danielkerr** [comment]
this was already addressed in the latest version

**Comment by TLEwebdevs** [comment]
Daniel,
When you say "in the latest version" ... which version do you mean?

It was certainly not fixed in the v2.0.1.1 download that I am building the site with, which was downloaded at the start of March 2015.  

So unless there has been a version upgrade since then, then it is not fixed in the latest version.

**Comment by aamnah** [comment]
version 2.0.2.0 was released on March 31st. [Download](http://www.opencart.com/index.php?route=download/download)

**Comment by TLEwebdevs** [comment]
Thank you - I was not aware that 2.0.2.0 had been released.

**Comment by atizva** [comment]
We are not able to successfully change the admin name. Please do let us know how to rename the admin folder for version 2.0.3.1.

Thanks
