### ISSUE TITLE
Error in addImage() of banner_form.tpl (admin\view\template\design)

### ISSUE THREAD

**Issue by TuSKan** [opencart/opencart#3705]
There is a missing " in line 107 in style after 10%

<p display: inline;>style="width: 10%<b style="color:red;">"</b>;</p>
```
html += '  <td class="text-right" style="width: 10%;><input type="text" name="banner_image[' + image_row + '][sort_order]" value="" placeholder="<?php echo $entry_sort_order; ?>" class="form-control" /></td>';
```

**Comment by danielkerr** [comment]
was fixed ages ago

**Comment by bruiseviolet** [comment]
It was not fixed ages ago- I just had this same exact error.

**Comment by mariurs** [comment]
Thanks, TuSKan! It was not fix in OC 2.1.0.2. Now it is thanks to you!
