### ISSUE TITLE
Cannot edit order when order reduces stock level to zero

### ISSUE THREAD

**Issue by nturne** [opencart/opencart#3811]
If an order for a product reduces the stock level of that product to zero then it is not possible to edit that order by going through 'Sales > Orders' then clicking the 'Edit' button for that order. When you get to step 2 'Products' a warning appears that states 'Products marked with *** are not available in the desired quantity or not in stock!'. This stops any edits from being saved.

In fact, it appears that the order edit is actually treating the edit as a new order. For example, if there are 1000 of a particular product in stock and a customer buys 501 of them, then the same behaviour is shown; although there are now 499 in stock the edit is blocked and the message 'Products marked with *** are not available in the desired quantity or not in stock!' is displayed.

I have tested this on a fresh install of the latest OpenCart (2.1.0.2) with default settings and no added extensions etc.

Please note that this apparent bug appears to have been previously reported under https://github.com/opencart/opencart/issues/3487 but was rejected.

**Comment by danielkerr** [comment]
this was fixed in the master branch

**Comment by nturne** [comment]
I have just retested this on a fresh install of the latest OpenCart (2.3.0.2) with default settings and no added extensions etc, but I am still getting the same 'Warning: Products marked with *** are not available in the desired quantity or not in stock!' message when trying to edit a product that has had its stock level reduced to zero through a sale.

**Comment by anupjrwe** [comment]
Sir please tell me if there is any solution for the above problem. It will be so pleasure.

**Comment by danielkerr** [comment]
You need to set the order to cancelled order status via the order info page
before editing the order

On 23 Aug 2016 6:54 p.m., "anupjrwe" <notifications@github.com> wrote:

Sir please tell me if there is any solution for the above problem. It will
be so pleasure.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/opencart/opencart/issues/3811#issuecomment-241695843>,
or mute the thread

**Comment by anupjrwe** [comment]
Thank you Sir.

It worked But its not a proper procedure to change status by first change status to cancelled and then set it to complete. How i supposed to tell my client like this way. Isn't there is any other option.

**Comment by danielkerr** [comment]
that is the correct procure!

when ever you alter any order it needs to be voided first!

technically most countries dont allow you to change an invoice once its
issued you have to void the old invoice and create a new one.

**Comment by anupjrwe** [comment]
Thank you sir. It was so pleasure that you help me.

**Comment by jeroencusters** [comment]
We are still on OC 2.0.3.1 and we can't update to the latest version right now. How can we solve this issue in the meanwhile? I can't find how/where/when it was fixed in the master branche. 

Thanks for your help!

**Comment by zetabyteUA** [comment]
Then why bother making a product editing function if it doesn't work?
The client calls by phone, wants to add another item to the order, but we cannot do this, and the manager needs to spend a lot of time creating a new order. This is not beneficial from the side of business processes.
Tell me, did someone find a solution?
