### ISSUE TITLE
Using reward points always provide fraud status when update status

### ISSUE THREAD

**Issue by aauwwo** [opencart/opencart#3947]
Wrong function confirm operator code.

catalog/model/total/reward.php line 68

Replace:
`if ($this->model_account_customer->getRewardTotal($order_info['customer_id']) < $points) {`

With:
`if ($this->model_account_customer->getRewardTotal($order_info['customer_id']) >= $points) {`

**Comment by danielkerr** [comment]
i think this was fixed ages ago

**Comment by aauwwo** [comment]
This issue just occur on 2.1.0.1 and still exist on 2.1.0.2.
