### ISSUE TITLE
2.2.0.0 upgrade error running install script

### ISSUE THREAD

**Issue by pnair39** [opencart/opencart#4055]
Notice: Error: Could not load model /home/amillio8/public_html/Demo/install/model/extension/extension.php! in /home/amillio8/public_html/Demo/system/storage/modification/system/engine/loader.php on line 63

**Comment by hughgodman** [comment]
I got the same error as pnair39.

There is no Folder for "/extension/" in the Install Folder:
	install/model/extension/extension.php

~~~~~160303 OC v2.2.0.0 Update - Instal Error~~~~~
Notice: Error: Could not load model
/home/cromwel6/hughmungous/install/model/extension/extension.php!
 in
/home/cromwel6/hughmungous/system/storage/modification/system/engine/loader.php
on line 82
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Hugh G.

**Comment by fiz1** [comment]
I got the same error too..

Notice: Error: Could not load model /home/........./public_html/install/model/extension/extension.php! in /home/wiwitzco/public_html/system/storage/modification/system/engine/loader.php on line 63

**Comment by McBochi** [comment]
Seems as if there are hell of a lot problems with the upgrade to 2.2.0.0 (coming from 2.1.0.2) in my case.
One example to add to the list:
The call for the Autoloader (https://github.com/opencart/opencart/blob/master/upload/system/startup.php#L86) causes a crash when open_basedir restrictions are in place...

**Comment by aj1322001** [comment]
same

**Comment by pnair39** [comment]
2.2.0.0 upgrade not possible according to the link below:

http://forum.opencart.com/viewtopic.php?f=181&t=158954

**Comment by pekka2** [comment]
Your need clear folder --- /modification

**Comment by pnair39** [comment]
clear what under system/storage/modification ?

**Comment by hughgodman** [comment]
Thanks "pnair39", I was also a bit perplexed at the Cryptic statement from "pekka2":
"Your need clear folder --- /modification".
I thought it may have been a piece of software! But after a long search down many Folders in Opencart I found system/storage/modification.
There are a heap of files in there.
Is this the area that "pekka2" is referring too??

**Comment by axelpetur** [comment]
I deleted all files in --/modification and then the it worked.

Thanks pekka2 ;)

**Comment by hughgodman** [comment]
Thanks axelpetur, I tried deleting all the files in system/storage/modification which did help with the install of Opencart 2.2.0.0 as it completed with "Successful".
- After I logged in I immediately after got errors "error undefined" twice.
- Did Ctrl F5 - Still got Error "error undefined" twice.
- All the Opencart Icon images were missing
- No link to any Extensions including Journal Theme.
- At this point I decided that Opencart 2.2.0.0 was still full of errors and NOT installable.
## Decided to revert back to V2.1.0.1 and wait for a future workable upgrade.

**Comment by opencarteli** [comment]
Try to delete all files and renew the db, then install it again
or create a new folder to install 2.2.0.0 ver, then apply your old data

**Comment by danielkerr** [comment]
ok so problem solved with clearing the modification directory.

**Comment by hughgodman** [comment]
Ref: danielkerr
Clearing the modification directory did not work for me.
OpenCart Version 2.2.0.0 is still not working for me as per my previous comments.
