### ISSUE TITLE
Mixed Content: HTTPS SSL issue

### ISSUE THREAD

**Issue by hendrachristian** [opencart/opencart#4102]
Found bug from clean install:
```
Error Message on Chrome while opening File Manager and Using Extension Installer:
Mixed Content: The page at 'https://www.primanada.com/admin/index.php?route=setting/setting&token=Glk0Da9ADfGraSIZPHkFr81l7plOYzMS' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.primanada.com/admin/index.php?route=common/filemanager&to…GraSIZPHkFr81l7plOYzMS&directory=demo&target=input-image&thumb=thumb-image'. This request has been blocked; the content must be served over HTTPS.
```
My site https://www.primanada.com is now reverted to use 2.1.0.2 for the time being.

Steps to reproduce:
1. Install OC 2.2.0.0 from empty folder, empty database (clean install)
File Manager
2. Go to Admin > System > Settings
3. Open File Manager to change one of the Image
4. Click on "demo" folder
5. Fails w/ above error message

Extension Installer
2. Go to Extensions > Extension Installer
3. Upload an OCMod
4. Fails w/ similar to above error message

I can't believe such a basic error bypass testing for OC 2.2.0.0.

PS: both config.php and admin/config.php have following values:
```
define('HTTP_SERVER', 'https://www.supermarketaudio.com/');
define('HTTPS_SERVER', 'https://www.supermarketaudio.com/');
define('HTTP_CATALOG', 'https://www.supermarketaudio.com/');
define('HTTPS_CATALOG', 'https://www.supermarketaudio.com/');
```
and Admin > System > Settings > Server > Use SSL set to "Yes"

**Comment by danielkerr** [comment]
i think should be fixed now. i put the urls system back to the way it was before 2.2

**Comment by hendrachristian** [comment]
I tried the changes manually on my OC 2.2 but it doesn't fix the issue. It still has the Mixed Content issue.

**Comment by hendrachristian** [comment]
I did some testing and found the following:
in Admin > System > Settings, the form is using http instead of https.
I checked that when it's calling `$this->url->link()`
system/library/url.php
`public function link($route, $args = '', $secure = false) {
if ($this->ssl && $secure) {
     $url = 'https://' . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SER    VER['SCRIPT_NAME']), '/.\\') . '/index.php?route=' . $route;
} else {
    $url = 'http://' . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SERV    ER['SCRIPT_NAME']), '/.\\') . '/index.php?route=' . $route; **===> it always arrive here, not the one above.**
}

if ($args) {
`
This is why it's failing and showing the Mixed Content problem.

**Comment by hendrachristian** [comment]
@danielkerr just checked recent commits, looks like you made a number of changes to the url.php file.  Going to download that and test it if it works on my server. Cheers.

**Comment by hendrachristian** [comment]
@danielkerr URL Mixed Content problem solved. Thanks. I found another problem with Language. I'll create a new Issue ticket for it.

**Comment by Dunky13** [comment]
I got this error with 2.2.0.0 - changed the url.php file to force https in either case. easiest hack fix for me. Hope next release has this fixed :)

**Comment by NeetiCollections16** [comment]
I have OpenCart 2.2.0.0 installation and I still have this issue even after I forced the HTTPS in the url.php. Please help.

**Comment by DrMTR** [comment]
I have the same issue. any help ?
