### ISSUE TITLE
OC2.2.0 SSL Error on checkout and payment

### ISSUE THREAD

**Issue by calderwood** [opencart/opencart#4276]
I noticed that the checkout was not changing to SSL while testing and is giving errors with PayPal Pro on Sandbox. Also PayPayPro iFrame does not work - I believe that again PP is not seeing the SSL.

I set all configs to https:// for secure and non-secure, If you  go to https://store then add product to cart, them go to cart, it reverts to non-ssl http://store  Same in admin  will not remain in SSL.

**Comment by leomb** [comment]
I too had inconsistent links; some https and some http when I checked the page source. I solved this problem by editing the **system > library > url.php** file. On line 18 I added the "s" after http even though it's supposed to be plain http. I know this is a hack; the real problem must be somewhere else but at least I can carry on for now.

**Comment by danielkerr** [comment]
version because i think this was fixed ageo ago

**Comment by calderwood** [comment]
Not fixed.  I installed a fresh 2.2.0 and the error is still there. The SSL does not work correctly.
