### ISSUE TITLE
Address book page 500 error

### ISSUE THREAD

**Issue by amirulahmad** [opencart/opencart#4563]
Link: /index.php?route=account/address

I got this when I enable the error reporting:
Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /path_to_www/catalog/controller/account/address.php on line 522 

which lead to:
elseif (($custom_field['type'] == 'text' && !empty($custom_field['validation'] && $custom_field['location'] == 'address')) && !filter_var($this->request->post['custom_field'][$custom_field['custom_field_id']], FILTER_VALIDATE_REGEXP, array('options' => array('regexp' => $custom_field['validation']))))

**Comment by danielkerr** [comment]
Was fixed ages ago replace the file with one from the master branch

**Comment by rohit-dhore** [comment]
I replaced the file "catalog/controller/account/address.php". still getting the same error.
