### ISSUE TITLE
Order status emails sent from wrong domain

### ISSUE THREAD

**Issue by moneycarlo** [opencart/opencart#4759]
I'm running 2.2 and have multistore set up.

I have 2 stores. Store1.com and store2.com.
When you place an order, you get your confirmation email from their respective domains.  (this is working fine).
However, when you update an order for store2.com and select notify customer, it kicks out the email from the store1.com domain.
My stores are not related in any way, so this is very confusing to the customer about why they're getting emails from a site/domain they've never had an interaction with.

**Comment by andrei-bogdan** [comment]
Hi, I have added a commit that should fix this.
Please review it and test those changes on your store.

**Comment by moneycarlo** [comment]
It creates a SyntaxError: Unexpected token < in JSON at position 0
see image
![error](https://cloud.githubusercontent.com/assets/10111666/17761378/4aaa90fc-64cc-11e6-965b-b2ed07a8b08b.jpg)

**Comment by andrei-bogdan** [comment]
Hi, I have fixed and updated the code. Can you check?
It seems fine on localhost now.

**Comment by moneycarlo** [comment]
Still an error if maxmind or fraudlabs are enabled (see image).  The email sends, but it's still from the wrong domain.  it has the correct store name as the from name, but the wrong domain, still showing store1.com.
![error](https://cloud.githubusercontent.com/assets/10111666/17800019/3437b9f6-65a5-11e6-8336-33b216cf5734.png)
Also, on step 6 of the checkout Confirm Order, i get the following error:
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model extension/total/voucher!' in /vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php:62 Stack trace: #0 /catalog/model/checkout/order.php(22): Loader->model('extension/total...') #1 [internal function]: ModelCheckoutOrder->addOrder(Array) #2 /vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(161): call_user_func_array(Array, Array) #3 [internal function]: Loader->{closure}(Array) #4 /system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #5 /catalog/controller/checkout/confirm.php(324): Proxy->__call('addOrder', Array) #6 /home/djpetesc/public_html/#7 [internal function]: ControllerCheckoutConfirm->index() #8 /vqmod/vqcache/vq2-system_storage_modification_system_engin in /vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 62
