### ISSUE TITLE
Warning: Shipping method required! - back again for 2.3.0.2!

### ISSUE THREAD

**Issue by losttheplot** [opencart/opencart#4903]
Have just updated a site to 2.3.0.2 and when checking out as a registered user, cannot get past the Delivery Method stage. No matter what is selected, I get "Warning: Shipping method required!"

I spent hours checking settings, different shipping methods, googling old issues to do with session regeneration, but could only get it working if I checked out as a guest.

Finally, I carried out a completely fresh 'demo data' install with a new db in a new vhost, with no extras whatsoever. I correctly set all file permissions and ownerships. I added two items to the basket and tried to checkout, only to find that I cannot get past the Delivery Method stage: "Warning: Shipping method required!"

So I'm reasonably sure this is a bug with 2.3.0.2! I'm using Chrome 53.0.2785.116 (64-bit) running on Mac 10.10.5.

**Comment by danielkerr** [comment]
this is a configuration issue not a bug!

**Comment by losttheplot** [comment]
That's not very helpful, @danielkerr . If you are confident that this is a configuration problem then maybe you could offer some suggestions as to what might be configured incorrectly - I have already spent a considerable amount of time trying different config scenarios. Secondly, if it is a config issue then maybe you should open up this issue again because as I said, the problem is apparent on a clean, off-the-shelf install set up in a new vhost with a new database, using the out-of-the-box 'demo' configuration.

**Comment by losttheplot** [comment]
To clarify the issue with a clean install of 2.3.0.2: Checking out as a guest works fine. Checking out as a previously registered account holder works fine. Checking out and registering an account at the same time results in "Warning: Shipping method required!" regardless of the shipping option selected.

**Comment by losttheplot** [comment]
I have spent many more hours on this today, repeating clean instals and different config settings, finally doing exactly the following (we have our own servers which are currently happily serving many other apps including older versions of OC):

1. Download and install latest zip file from OC website (2.3.0.2).
2. Completely empty target vhost and clear all associated cookies.
3. Upload 'upload' dir to vhost.
4. Set ownership and permissions to webdev:apache 775 for installation (only).
5. Run OC installer script from browser (driver: PDO, language: UK) ...success.
6. Delete install directory.
7. Login to admin and set Macbook (Product 16) to 'requires shipping' and 'In Stock'.
8. Confirm store settings country set to UK, and enter a UK Geocode for region.
9. Confirm Geo Zone set-up for UK Shipping (UK, all zones).
10. Confirm Geo Zone set-up for UK VAT Zone (UK, all zones).
11. Confirm Tax Class set for Taxable Goods (VAT, based on shipping address).
12. Confirm COD enabled as Payment Method with Geo Zone set to 'All Zones'.
13. Confirm FRS enabled as Shipping option with Geo Zone set to 'All Zones'.
14. Also confirm FRS (Flat Rate Shipping) set to Tax Class of 'Taxable Goods'.
15. From front-end: add Macbook to cart and checkout as 'Register Account'.
16. Fill out form as UK buyer and tick 'same addresses' and 'agree PP'.
17. Issue: "Warning: Shipping method required!"
18. Admin area: specifically set COD delivery Geo Zone to 'UK Shipping'.
29. Admin area: specifically set Flat Rate Shipping Geo Zone to 'UK Shipping'.
30. Try to checkout again: "Warning: Shipping method required!"
31. Admin area: add/enable Pickup from Store and set Geo Zone to 'UK Shipping'.
32. Try to checkout again with either option: "Warning: Shipping method required!"

I have even tried doing all of the above with the latest 2.3.0.3_rc codebase from github, and in this case could not even get past "Warning: No Payment options are available.", which is a different problem but along the same lines.

If you could let me know what I'm doing wrong, I would be most grateful.

**Comment by losttheplot** [comment]
UPDATE (for the benefit of anyone with similar problems, that ends up reading this):

@osworx has very kindly spent the last few days trying to help me get to the bottom of this problem. He has shown that the checkout shipping error was being triggered because the session variable 'shipping_method' was being lost from the session data at the point that the 'shipping' stage of the checkout form was actioned. Interestingly, 'shipping_method' is a multi-dimensional array:
```
[shipping_methods] => Array
        (
            [flat] => Array
                (
                    [title] => Flat Rate
                    [quote] => Array
                        (
                            [flat] => Array
                                (
                                    [code] => flat.flat
                                    [title] => Flat Shipping Rate
                                    [cost] => 5.00
                                    [tax_class_id] => 9
                                    [text] => $8.00
                                )
                        )
                    [sort_order] => 1
                    [error] => 
                )
        )
)
```
By installing and testing clean copies of OC of various versions on various platform configurations with various PHP config settings, I noticed that the 'shipping_methods' array was being lost on the CentOS with PHPv5.6.26 platform that was using redis and phpredis for session storage. This is a fairly standard set-up for enterprise servers and is not known for having issues handling the serialisation of multidimensional arrays.

On changing this set-up to use 'files' for session storage, the problem disappeared in my initial tests, but OSWorX is not convinced that redis is the cause of the problem so is going to carry out some more tests.

If you are reading this and have any theories or experiences that might help understand why 'shipping_method' is being lost from the session data, please add to this discussion.

**Comment by anhtuan29592** [comment]
@losttheplot Have you resolved the problem when storing session by using redis? I have the same issue when using redis handler, 'shipping_methods' has been lost and 'Warning: Shipping method required!' appears. But the error doesn't appears when using session files handler...
Some information of system: AWS php v5.6.30, phpredis module v3.1.1, session.serialize_handler=php

Thanks.

**Comment by losttheplot** [comment]
@anhtuan29592 - No, this was not a resolvable issue for us, even though @danielkerr closed the thread at the first opportunity. As good as OC is for small shops running on commercial hosting platforms, we had clearly outgrown it, so we looked at alternative engines. 

We gave Prestashop a thorough testing but generally speaking it is a very similar product with similar limitations if you move beyond standard commercial hosting.

So we switched to Magento 2 CE and are in the middle of putting our first M2 shop together. M2 is way more complex that OC, extensions cost a lot more (generally speaking), and it requires some serious server resources to get it running at a decent speed. However, if you're at home with a CLI and if you're hitting issues like the one in this thread, then it might be time for you to follow suit, because everything about M2 is professional and enterprise-level in its approach and deployment.

**Comment by losttheplot** [comment]
...and there's another reason to consider other ecommerce engines, sadly.

**Comment by maicho** [comment]
> is it professional to not design your software to run on shared host!
I think Redis is the best choice for using now? 
Our customer want to use the Redis , they don't use "File" to store session.

**Comment by Thargelion** [comment]
I had the same problem when testing OC3 in IE11. Fixed cleaning cache (CTRL + SHIFT + DEL). This may not be the solution to the original thread but I hope it helps another person searching for it.

**Comment by qphoria** [comment]
It is a bug with IE... the fix is here:
http://forum.opencart.com/viewtopic.php?f=20&t=98579&p=395258#p394521
For 3.0 you'll need to change that .tpl to .twig but it should work for all versions.
Be sure you refresh your twig cache and modifications after adding the vqmod or making the changes manually.

**Comment by Shifterovich** [comment]
This happens on my 3.0.2.0 as well, though rarely -- which is the annoying part of it. It's hard to fix because it's hard to reproduce. Refreshing the page works (so if I don't manage to fix it on the backend, I might end up adding `location.reload()` to the error message).

**Comment by danielkerr** [comment]
Im working on this now. it requires ajax calls to be chained so they are called one after another instead of some being done concurrently.

**Comment by stub1000** [comment]
I'm certainly experiencing the problem on v3.0 of opencart, and its easily reproducible:

If you check out, then abandon the pay element and then try to re-checkout you get :
'Warning: Shipping method required!' , even though the tick box is already ticked.

The post from http://forum.opencart.com/viewtopic.php?f=20&t=98579&p=395258#p394521 seems to hint at a solution, but I have no idea on how to apply it to v3 as its based on .twig rather than .tpl

**Comment by danielkerr** [comment]
its fixed in the master what ever it was.

**Comment by stub1000** [comment]
lol, that reply makes absolutely no sense what so ever. 

unfortunately its not resolved, which is why I went to the effort of typing my comments on this thread.

**Comment by Shifterovich** [comment]
I'll try to code the bug fix myself then. I guess chaining the requests using promises is a good solution.

**Comment by danielkerr** [comment]
im certain its the same issue. the system makes multiple requests on the checkout page and can cause the session to be overwritten. the country / zone ajax request is called while shipping or payment methods are being generated.

**Comment by danielkerr** [comment]
also i dont fix issues on older version. just ones reported in the latest releases.

**Comment by Shifterovich** [comment]
Pretty sure 3.0.2.0 is the latest release.
![screenshot from 2018-08-01 19-02-39](https://user-images.githubusercontent.com/4354706/43536666-78608e2e-95bd-11e8-8343-fd0a4f5e14d5.png)

**Comment by MrPlow254** [comment]
@Shifterovich he isn't meaning the "release" but the working developer builds. Currently on build number 9030 which is the current commit number

**Comment by Shifterovich** [comment]
This is a problem with OpenCart releases system. Stable releases should receive bug fixes. There hasn't been a single update since July 17 2017, which is over a year ago.

**Comment by MrPlow254** [comment]
I would agree with you if this wasn't an opensource program. I would be outraged as well only if this was proprietary. Errors in the program can easily be debugged and fixed if you know what you are doing. If you don't know what you are doing then how the hell did you get a website running lol

**Comment by Shifterovich** [comment]
Fun fact: OpenCart is very user-friendly and you can install it without *any* programming knowledge.

There are some people who know the basics of web hosting, HTML etc -- people capable of maybe changing the views a little bit. But I doubt more than 5% of OpenCart administrators are capable of fixing an ajax race condition.

**Comment by mrHiker** [comment]
Hi everyone,
I had the same issue on 2.1.0.2.1 , php 5.6, Redis enabled.

I tried to disable cache as described here http://forum.opencart.com/viewtopic.php?f=20&t=98579 with no result.
When I switched to php 7.1 and disabled redis the problem's gone! 
@losttheplot, @anhtuan29592 thanks guys, you saved my day!
Does anybody know what negative impact can I face changing session handler?

@danielkerr can you please be more specific about the fix you've done? Thanks

**Comment by AbdelReheem** [comment]
@danielkerr Issue still exist as I'm using OC3.0.3.1 and I'm in this from around 10 days and i tried all and every thing here and in opencart community, Could you please help me fix this as I figured the problem after moving the development into live website and I'm trapped now and must fix it and no one can use the website because of this error. 

the only way was disabling all the header cache for the whole website which slow down the speed and cause a conflict in the server after 2 days !! Please Support with any temporary solution till your next release.
 
@qphoria I changed .tpl to .twig and still the issue exist and by the way on OC 3.0.3.1 error appeared in all and every thing chroom firfox safari all browser, you just reach confirm order then return back to change anything in your order selection and you get the Warning: Shipping method required! Any suggestions.

**Comment by ADDCreative** [comment]
@AbdelReheem It could be this issue. https://github.com/opencart/opencart/issues/7008

Try making the changes in the following forum post, to see if it helps.
https://forum.opencart.com/viewtopic.php?f=201&t=207498#p737430

**Comment by AbdelReheem** [comment]
@ADDCreative Really appreciate your reply, I tried disabling header cache before and this cause a HTTP Error 500, Also the problem exist with all browser not only IE 11
So if this header solve the issue with all browser and will not crash the server for sure will use it.

@qphoria I got this fixed yesterday by disabling the checkout cache, as i'm using default checkout page so I created the vqmod for the default theme but it didn't work after my comment post here and as a trial I created another one pointing to the theme checkout which i'm not using but finally it work 💯 .

**Comment by ADDCreative** [comment]
@AbdelReheem The lack of cache control headers could also affect other web browsers. If you get 500 Internal Server Errors just by adding some cache control headers to PHP, then that would point to a server issue.

**Comment by AbdelReheem** [comment]
@ADDCreative first of all I would like to thank you for your support as your comments as it help me fixing other issues I was facing, for server error - to be honest I don't know as I upgraded my server php from PHP 5 to PHP 7 for installing and check the beta of OC 3.1, so as per logic OC 3.0.3 required PHP 5 or more so using PHP 7 will not cause the crash and no need to downgrade to PHP 5, Am I right !!

**Comment by ADDCreative** [comment]
@AbdelReheem OpenCart 3.x should work fine on PHP 7 as far as I'm aware.

**Comment by AbdelReheem** [comment]
@ADDCreative @qphoria thanks for all your support and replies I really appreciate it it help me a lot.
@danielkerr Thanks for all the team OC 3.x is amazing, it just hard to deal with it, great work

**Comment by osworx** [comment]
OpenCart 3.x is working very fine with php 7.x
There, 7.2 should be used (NOT 7.1.x).
One benefit is: approx. 20-30% more speed

**Comment by AbdelReheem** [comment]
@osworx Thanks for the info I'm using 7.1 as 7.2 still not available on my server, will use it for sure soon

**Comment by AbdelReheem** [comment]
@danielkerr Just a feedback, I replaced the Ajax chained files from the master with my OC 3.0.3.1 installation and still the issue exist shipping method required.

I think feedback will support in your success journey and in your project.
Hope all the success to you and all your team as you support all the users of Opencart

**Comment by danielkerr** [comment]
i think i added them in the master branch

**Comment by djlaserman** [comment]
> That's not very helpful, @danielkerr . If you are confident that this is a configuration problem then maybe you could offer some suggestions as to what might be configured incorrectly - I have already spent a considerable amount of time trying different config scenarios. Secondly, if it is a config issue then maybe you should open up this issue again because as I said, the problem is apparent on a clean, off-the-shelf install set up in a new vhost with a new database, using the out-of-the-box 'demo' configuration.

Problem still there in 3.0.3.6 ! With all the xml mod in and no errors in the log

**Comment by djlaserman** [comment]
![image](https://user-images.githubusercontent.com/41134053/105835522-973d1400-5fd4-11eb-9a11-1c3a642a1a5e.png)

**Comment by redochka** [comment]
Solution: https://github.com/opencart/opencart/issues/7811#issuecomment-830641855
