### ISSUE TITLE
System deletes the files with same as folder name

### ISSUE THREAD

**Issue by ersanserkan** [opencart/opencart#5296]
I created a folder with with name logo in filemanager. When I delete the folder, the logo.png was deleted at the same time with folder. The system deletes the files with same as folder name

**Comment by arnisjuraga** [comment]
@ersanserkan is right! I just tested it, and on 2.3.0.2 version - if you select to delete a folder "logo" while you have an image "logo.png" in the same folder - both image and the folder is deleted. Must be fixed! @danielkerr please, confirm.

**Comment by danielkerr** [comment]
ther should be a is_dir or is_file

**Comment by arnisjuraga** [comment]
The problem is not with `is_dir` or `is_file`, but with the `glob` as it is used with wildcard.
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php?ts=2#L397
https://github.com/opencart/opencart/blob/master/upload/admin/controller/common/filemanager.php?ts=2#L400

Also, current solution will not delete "hidden files", that's why it will return ERROR, if directory contains hidden files! 

Simplify solution with this:

https://github.com/opencart/opencart/pull/5306

**Comment by danielkerr** [comment]
i know the issue!

**Comment by danielkerr** [comment]
and ur commits are crap!

do u see me using the word del any where? delTree

**Comment by danielkerr** [comment]
fixed with on char removed!

better than writing a whole new function

**Comment by RaidoDev** [comment]
@danielkerr - your solutions is partly fixed. The solution still does not delete hidden files. 
It now don't delete files with the same name, but deleting folders with hidden files, still will give an error: 

`<b>Warning</b>: rmdir(/public_html/upload/image/catalog/cart): Directory not empty in <b>/public_html/upload/admin/controller/common/filemanager.php</b> on line <b>425</b>{"success":"Success: Your file or directory has been deleted!"}`
