### ISSUE TITLE
Product options missing while updating product 

### ISSUE THREAD

**Issue by wforfun** [opencart/opencart#6234]
I found out the error by the process below:
1. Navigate to catalog > products -> Product option
2. Add new product option for product A
3. Navigate to catalog > products -> Product
4. Find product A and update 
5. Go back catalog > products -> Product option. Now Product option for product A is missing.

Here's why. When updating product information, all the option and option value of that product will be deleted.
After that, if in the POST data have $data['product_option'] then product option will be reinserted.
```
$this->db->query("DELETE FROM " . DB_PREFIX . "product_option WHERE product_id = '" . (int)$product_id . "'");
$this->db->query("DELETE FROM " . DB_PREFIX . "product_option_value WHERE product_id = '" . (int)$product_id . "'");

		if (isset($data['product_option'])) {
			foreach ($data['product_option'] as $product_option) {
				if ($product_option['type'] == 'select' || $product_option['type'] == 'radio' || $product_option['type'] == 'checkbox' || $product_option['type'] == 'image') {
					if (isset($product_option['product_option_value'])) {
						$this->db->query("INSERT INTO " . DB_PREFIX . "product_option SET product_option_id = '" . (int)$product_option['product_option_id'] . "', product_id = '" . (int)$product_id . "', option_id = '" . (int)$product_option['option_id'] . "', required = '" . (int)$product_option['required'] . "'");

						$product_option_id = $this->db->getLastId();

						foreach ($product_option['product_option_value'] as $product_option_value) {
							$this->db->query("INSERT INTO " . DB_PREFIX . "product_option_value SET product_option_value_id = '" . (int)$product_option_value['product_option_value_id'] . "', product_option_id = '" . (int)$product_option_id . "', product_id = '" . (int)$product_id . "', option_id = '" . (int)$product_option['option_id'] . "', option_value_id = '" . (int)$product_option_value['option_value_id'] . "', quantity = '" . (int)$product_option_value['quantity'] . "', subtract = '" . (int)$product_option_value['subtract'] . "', price = '" . (float)$product_option_value['price'] . "', price_prefix = '" . $this->db->escape($product_option_value['price_prefix']) . "', points = '" . (int)$product_option_value['points'] . "', points_prefix = '" . $this->db->escape($product_option_value['points_prefix']) . "', weight = '" . (float)$product_option_value['weight'] . "', weight_prefix = '" . $this->db->escape($product_option_value['weight_prefix']) . "'");
						}
					}
				} else {
					$this->db->query("INSERT INTO " . DB_PREFIX . "product_option SET product_option_id = '" . (int)$product_option['product_option_id'] . "', product_id = '" . (int)$product_id . "', option_id = '" . (int)$product_option['option_id'] . "', value = '" . $this->db->escape($product_option['value']) . "', required = '" . (int)$product_option['required'] . "'");
				}
			}
		}```
But in the product form (admin/view/template/catalog/product_form.twig) there is none product_option been created. 
So I checked function getForm (admin/controller/catalog/product.php) but there is no data involved product option returned.

**Comment by stalker780** [comment]
#6156 
Daniel didn't merge it. Don't know why. Maybe he has own plans for this functionality, but options are broken for now.

**Comment by danielkerr** [comment]
fixed int he last commit

**Comment by danielkerr** [comment]
@stalker780  because i didn't see you pull request!~

**Comment by howdu** [comment]
@danielkerr product options tab is still missing. Not sure why it was purposely removed  https://github.com/opencart/opencart/commit/425535e6295430439de2ea02213901b779755744

**Comment by howdu** [comment]
Check you have all the user group permissions to see the new menu option. It has been moved to a separate page not a tab.
