### ISSUE TITLE
[v3.0.2.0 - Possible Fix] - Increasing length of URL for MD5 hash with Sagepay Server

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6274]
On the Opencart forum, I have found a "possible" fix that may resolve the long time reported issue with the Sagepay Server: https://forum.opencart.com/viewtopic.php?f=198&t=200601 . Either increasing the length of the URL tolerance or to parse the payment_data array similarly to what Stackoverflow suggests.

**Comment by straightlight** [comment]
Forum OP user confirms issue has been resolved with Sagepay Server with provided solution on the forum topic.

**Comment by JesseOC** [comment]
Sagepay still not have an official reply.
But already fixed on #6301
