### ISSUE TITLE
Checkout Gets Stuck on Payment Method when Reviewing Cart

### ISSUE THREAD

**Issue by Opencartman** [opencart/opencart#6600]
This bug manifests itself only when Registering a New Customer Account and then Reviewing the Shopping Cart, i.e. it will not happen when pressing 'Checkout' directly - one must first click on the 'Shopping Cart' link in the upper toolbar or on the black Cart Button, then 'View Cart' link (again, if one clicks on the black Cart Button, then on the 'Checkout' link within, without reviewing the cart, the bug won't be triggered). Also it happens irregularly, in about 50-75% of cases on average.

OpenCart gets stuck on the 'Payment Method' with the error message "Warning: Payment method required!" even though the payment method is pre-selected.

I have firstly thought that this is caused by a lack of the second radio button choice (as I have started getting this error with only a single Payment Provider). But as you can see from the attached screenshot, it happens even with the two Payment Providers and two Radio Buttons to choose from.

There is a work-around, which I found: Pressing a F5 (Refresh) button repeats the previous step (Billing Details) and the Payment Method gets 'un-stucked' - this is however a very awkward work-about, as the customer won't obviously know about this possibility and probably just gives up after several attempts - therefore it is a serious functional bug, costing the host of the e-shop customers and sales.

![opencart bug](https://user-images.githubusercontent.com/38534381/39002971-b53475d6-43f1-11e8-97d0-662d6601c499.png)

**Comment by AlexChanHK** [comment]
Hi @Opencartman 
Are you using A2 hosting?
As there are similar case existed when user choose A2 hosting.

**Comment by danijelGombac** [comment]
I had similar problem, in my case was session problem.

I fixed it by adding a check for session in save function:

```
if (!isset($this->request->post['payment_method'])) {
    $json['error']['warning'] = $this->language->get('error_payment');
} else {
    if (!isset($this->session->data['payment_methods'])) {
        // Totals
        $totals = array();
        $taxes = $this->cart->getTaxes();
        $total = 0;

        // Because __call can not keep var references so we put them into an array.
        $total_data = array(
            'totals' => &$totals,
            'taxes'  => &$taxes,
            'total'  => &$total
        );
        
        $this->load->model('setting/extension');

        $sort_order = array();

        $results = $this->model_setting_extension->getExtensions('total');

        foreach ($results as $key => $value) {
            $sort_order[$key] = $this->config->get('total_' . $value['code'] . '_sort_order');
        }

        array_multisort($sort_order, SORT_ASC, $results);

        foreach ($results as $result) {
            if ($this->config->get('total_' . $result['code'] . '_status')) {
                $this->load->model('extension/total/' . $result['code']);
                
                // We have to put the totals in an array so that they pass by reference.
                $this->{'model_extension_total_' . $result['code']}->getTotal($total_data);
            }
        }

        // Payment Methods
        $method_data = array();

        $this->load->model('setting/extension');

        $results = $this->model_setting_extension->getExtensions('payment');

        $recurring = $this->cart->hasRecurringProducts();

        foreach ($results as $result) {
            if ($this->config->get('payment_' . $result['code'] . '_status')) {
                $this->load->model('extension/payment/' . $result['code']);
                $method = $this->{'model_extension_payment_' . $result['code']}->getMethod($this->session->data['payment_address'], $total);
                if ($method) {
                    if ($recurring) {
                        if (property_exists($this->{'model_extension_payment_' . $result['code']}, 'recurringPayments') && $this->{'model_extension_payment_' . $result['code']}->recurringPayments()) {
                            $method_data[$result['code']] = $method;
                        }
                    } else {
                        $method_data[$result['code']] = $method;
                    }
                }
            }
        }

        $sort_order = array();

        foreach ($method_data as $key => $value) {
            $sort_order[$key] = $value['sort_order'];
        }

        array_multisort($sort_order, SORT_ASC, $method_data);
        
        $this->session->data['payment_methods'] = $method_data;
    }

    if (!isset($this->session->data['payment_methods'][$this->request->post['payment_method']])) {
        $json['error']['warning'] = $this->language->get('error_payment');
    }
}
```

**Comment by Opencartman** [comment]
Hi Alex.

 

No, I am using iPage hosting.

 

Cheers.

 

Louis

 

Sent: Friday, April 20, 2018 at 6:58 AM

**Comment by danijelGombac** [comment]
@Opencartman 

https://github.com/opencart/opencart/blob/eb29c012c17d2fb278e0decfcfcfca04110ec7b7/upload/catalog/controller/checkout/payment_method.php#L159,L163

**Comment by deepabhakuni** [comment]
I tried the solution given by Danijel but still the same issue is occurring. Can anyone else help me with this?

**Comment by Opencartman** [comment]
Yes, me too - that 'solution' doesn't work :o(
 

Sent: Wednesday, May 02, 2018 at 8:09 AM

**Comment by Opencartman** [comment]
UPDATE:

I've done a bit of digging and found that the error is triggered in the module 'payment_method.php' on this line:
		elseif (!isset($this->session->data['payment_methods'][$this->request->post['payment_method']]))
		{
			$json['error']['warning'] = $this->language->get('error_payment');
		}

... and it is $this->session->data['payment_methods'] part of the ELSEIF condition that is losing the value (the second part $this->request->post['payment_method'] seems to be keeping its value fine).

So the problem must be somewhere in code preceding 'payment_method.php' where $this->session->data['payment_methods'] is being filled with data, and this data not being passed in certain circumstances into 'payment_method.php'.

**Comment by danielkerr** [comment]
I fixed this issue previously using chained ajax calls.

if you need a fix u could probably copy the checkout page twig code and common.js

you would need to search my commit history.

**Comment by danielkerr** [comment]
FYI i think the issue is related to ajax calls in the background causing the session to overwite its self.

**Comment by deepabhakuni** [comment]
I've used the chained ajax calls. Copied the checkout page twig code and common.js but still the same issue is occurring.  Is there anything else that I am missing here?

**Comment by ultrono** [comment]
> I had similar problem, in my case was session problem.
> 
> I fixed it by adding a check for session in save function:
> 
> ```
> if (!isset($this->request->post['payment_method'])) {
>     $json['error']['warning'] = $this->language->get('error_payment');
> } else {
>     if (!isset($this->session->data['payment_methods'])) {
>         // Totals
>         $totals = array();
>         $taxes = $this->cart->getTaxes();
>         $total = 0;
> 
>         // Because __call can not keep var references so we put them into an array.
>         $total_data = array(
>             'totals' => &$totals,
>             'taxes'  => &$taxes,
>             'total'  => &$total
>         );
>         
>         $this->load->model('setting/extension');
> 
>         $sort_order = array();
> 
>         $results = $this->model_setting_extension->getExtensions('total');
> 
>         foreach ($results as $key => $value) {
>             $sort_order[$key] = $this->config->get('total_' . $value['code'] . '_sort_order');
>         }
> 
>         array_multisort($sort_order, SORT_ASC, $results);
> 
>         foreach ($results as $result) {
>             if ($this->config->get('total_' . $result['code'] . '_status')) {
>                 $this->load->model('extension/total/' . $result['code']);
>                 
>                 // We have to put the totals in an array so that they pass by reference.
>                 $this->{'model_extension_total_' . $result['code']}->getTotal($total_data);
>             }
>         }
> 
>         // Payment Methods
>         $method_data = array();
> 
>         $this->load->model('setting/extension');
> 
>         $results = $this->model_setting_extension->getExtensions('payment');
> 
>         $recurring = $this->cart->hasRecurringProducts();
> 
>         foreach ($results as $result) {
>             if ($this->config->get('payment_' . $result['code'] . '_status')) {
>                 $this->load->model('extension/payment/' . $result['code']);
> 
>                 $method = $this->{'model_extension_payment_' . $result['code']}->getMethod($this->session->data['payment_address'], $total);
> 
>                 if ($method) {
>                     if ($recurring) {
>                         if (property_exists($this->{'model_extension_payment_' . $result['code']}, 'recurringPayments') && $this->{'model_extension_payment_' . $result['code']}->recurringPayments()) {
>                             $method_data[$result['code']] = $method;
>                         }
>                     } else {
>                         $method_data[$result['code']] = $method;
>                     }
>                 }
>             }
>         }
> 
>         $sort_order = array();
> 
>         foreach ($method_data as $key => $value) {
>             $sort_order[$key] = $value['sort_order'];
>         }
> 
>         array_multisort($sort_order, SORT_ASC, $method_data);
>         
>         $this->session->data['payment_methods'] = $method_data;
>     }
> 
>     if (!isset($this->session->data['payment_methods'][$this->request->post['payment_method']])) {
>         $json['error']['warning'] = $this->language->get('error_payment');
>     }
> }
> ```

Thought I'd leave a reply here in case people land on the page via Google.

@danijelGombac That's such a good and bad solution at the same time :) Good in the respect that you've copied code block from one place to another. However, this has solved on ongoing issue we've had, we are running Version 3.0.2.0.

**Comment by apartamenti** [comment]
I can confirm this solutions is working on Opencart 3.0.3.2! Thank you guys!

**Comment by redochka** [comment]
Another solution https://github.com/opencart/opencart/issues/7811#issuecomment-830641855
