### ISSUE TITLE
Paypal payflow pro: recurring payment fails

### ISSUE THREAD

**Issue by thunbtack** [opencart/opencart#6624]
With a product which requires a monthly subscription (on the recurring tab for that product, there is a monthly profile), when we get to the checkout payment page, we get "payment method not available".  Paypal payflow pro is capable of taking recurring payments and has been set up to do that.  If the product is changed so that it takes only a single payment to purchase it, the module works properly.

Please fix asap, or if not that, advise as to which currently available module will take recurring payments.

**Comment by danielkerr** [comment]
this has been fixed in the master

**Comment by danielkerr** [comment]
https://github.com/opencart/opencart/issues/5084

**Comment by thunbtack** [comment]
Recurring still does not work with Paypal payflow pro; opencart dashboard says opencart version 3.1.0.0alpha; should I switch to PayPal Express?
