### ISSUE TITLE
v3.0.2.0 Cart labeled "Use Gift Certificate" instead of "Shopping Cart"

### ISSUE THREAD

**Issue by TheRealDJ** [opencart/opencart#6681]
OpenCart Version: 3.0.2.0
PHP Version: 5.4.40

Cart Title: "Use Gift Certificate (1.00lb)"
Should Be: "Shopping Cart (1.00lb)"

**Comment by danielkerr** [comment]
i think this was fixed ages ago.

**Comment by newerton** [comment]
It's still wrong.
![image](https://user-images.githubusercontent.com/4175945/54384952-38867f80-4674-11e9-8071-7be5d813bbfe.png)

Opencart Version: 3.0.3.1
PHP Version: 7.2

**Comment by condor2** [comment]
Because fixed bugs from 3.0.2.0 hasn't added on 3.0.3.1.

You need to add `$data['heading_title'] = $this->language->get('heading_title');` on some controller, account, adresses....etc
