### ISSUE TITLE
Theme editor overrides OCMOD modifications

### ISSUE THREAD

**Issue by v5manoel** [opencart/opencart#6758]
If an OCMOD modification changes the same theme file changed through the Theme Editor, the OCMOD modifications are completely ignored.

Theme Editor is an excellent tool, but it does not work with OCMOD, and this is a serious problem.

The problem occurs in file:
catalog/controller/event/**theme.php**

In the code below, if the file was edited through the Theme Editor, it simply ignores the file edited through OCMOD.

```
// If there is a theme override we should get it
$this->load->model('design/theme');

$theme_info = $this->model_design_theme->getTheme($route, $directory);

if ($theme_info) {
	$code = html_entity_decode($theme_info['code'], ENT_QUOTES, 'UTF-8');
}
```
In version 3.1.0.0_a1 the problem persists.

One solution to solve the problem would be to create the OCMOD cache by looking for the file edited through the Theme Editor, but some modifications would have to happen in the Theme Editor because it allows themes to be edited by store selected. Being the ideal edit by theme folder selected.

**Note:** Sorry if my english is not good. I hope we find a solution to this serious problem.

**Comment by danielkerr** [comment]
already fixed in the alpha release.

theme modifications need to be done via lamba functions added in the pre load event.

**Comment by v5manoel** [comment]
@danielkerr Could you give an example of how it will work?

**If I were to edit the product details page, I should put in the install of my module:**

`$this->model_setting_event->addEvent('my_event', 'catalog/view/product/product/after', 'extension/module/my_module/after');`

**And in the controller of my module:**

public function after(&$route, &$args, &$output) {
 // My code
}

**Note:** I already use the OpenCart event system, and I know that in $ output the page code is rendered. What I question is how I can practically change the code the same way I would in OCMOD.

**Comment by mhcwebdesign** [comment]
Daniel, it's still not working. The theme editor still causes OCmod changes to be ignored. Also, the theme editor is only working when theme caching is turned on. Using lambda functions for template modifications is just a convoluted design.

**Comment by danielkerr** [comment]
Its not going to work with the theme editor. 

use events instead of ocmod.

**Comment by mhcwebdesign** [comment]
We use event handlers for template changes all the time. But your OpenCart market is full of 3rd party extensions that use OCmod or VQmod for template modifications. And your latest OC 3.1.0.0.a1 has changed the view/*/before event handler method signature again, thus breaking backward compatibility. There is no reason why event handlers couldn't work without the need of lambda functions!

**Comment by mhcwebdesign** [comment]
Just a thought: Can't we use the Twig_Extension_StringLoader for cases where modifications were done via 1) Theme Editor, 2) OCmod, or 3) event Handlers. In each of these cases there ought to be a string buffer containing the modified template which is then passed on to the Twig rendering engine.

**Comment by danielkerr** [comment]
ok will look to this.

**Comment by danielkerr** [comment]
if there is a mod file found it will grab the contents for that. 

adding a text notification if using a mod file or original might be better?

**Comment by v5manoel** [comment]
Ideally, when updating the ocmod cache, check if there is a theme file edited by the OpenCart theme editor, and apply the OCMOD modifications in edited file.
