### ISSUE TITLE
session table bloated

### ISSUE THREAD

**Issue by exit15** [opencart/opencart#7094]
**What version of OpenCart are you reporting this for?**
3.0.2.0
**Describe the bug**
expired session data not deleted from session table, causing massive bloat

**To Reproduce**
[SQL] delete from `session` where `session`.expire < DATE_SUB(NOW(), INTERVAL 1 DAY);
Affected rows: 4421650
Time: 31.098ms

**Expected behavior**
To delete old session records, not sure what the interval is, but it never does. As you can see i accumulated ~4.5 million records

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
Deployed to a web server www.searchwellness.com
 - CentOS Linux 7.6.1810 (Core)
 - PHP version 5.6.39
 - Apache version 
 - Browser(s) tested with [chrome, firefox]

**Additional context**
tried replacing /httpdocs/system/library/session/db.php with latest version from this repository, did not work.

**Comment by danielkerr** [comment]
its set at php level. 

1. open php.ini
2. edit session.cookie_lifetime = 3600

**Comment by exit15** [comment]
Thanks, my value was set to 0, when I set it to 3600, I could not login to the cart admin and the website could not maintain a session (cart content kept deleting).

What can it be?

You did not say anything about system/library/session/db.php, so I tried copying the version from github, to no avail and so I rolled that back and php.ini (server_wide)

 

What now?

**Comment by danielkerr** [comment]
You need to set your db time zone and php time zone the same.

**Comment by exit15** [comment]
It is the same:

 

SQL:

SELECT NOW();

2018-12-11 01:50:40

 

System time       

2018 December 11

01 :50 :20

Time zone

Your time zone 

Network time

 

PHP.ini

Timezone Database        internal

Default timezone             America/New_York

**Comment by danielkerr** [comment]
I need to put some code there so it sets the mysql db time zone the same as php.

**Comment by danielkerr** [comment]
You can set the system time zone for MySQL Server at startup with the --timezone=timezone_name option to mysqld_safe. You can also set it by setting the TZ environment variable before you start mysqld. The permissible values for --timezone or TZ are system dependent. Consult your operating system documentation to see what values are acceptable.

**Comment by exit15** [comment]
First off my system/framework.php is not the same as the github version (downloaded on 12/09/2018)
But when I copied the most recent version i got this error:

Exception: Error: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
Error No: 1227
SET GLOBAL time_zone = '+00:00' in /var/www/vhosts/exit15.com/httpdocs/system/library/db/mysqli.php on line 40

**Comment by mycncart** [comment]
get error:
 Notice: Undefined variable: db in xxx\catalog\controller\startup\startup.php on line 35Error: Call to a member function query() on null in \catalog\controller\startup\startup.php on line 35

**Comment by danielkerr** [comment]
download the master and replace the framework file on your site.

**Comment by mycncart** [comment]
Yes. User the latest master and get this error. Maybe the startup.php nees to remove the line 35: $db->query("SET time_zone = '" . $db->escape(date('P')) . "'");

**Comment by danielkerr** [comment]
Undefined variable: db error is not a query error!

and startup.php has nothing to do with the db!

i'm not sure what u have done but seems u have modified the code!

**Comment by mycncart** [comment]
Downloaded the master today and installed it, and got this error. I mean there is  $db->query("SET time_zone = '" . $db->escape(date('P')) . "'");  on line 35  and this caused this error.

**Comment by danielkerr** [comment]
ok seems no other complaints so i will close this soon.

**Comment by danielkerr** [comment]
use this

$this->db->query("DELETE FROM " . DB_PREFIX . "session WHERE expire < '" . $this->db->escape(date('Y-m-d H:i:s', time())) . "'");

**Comment by exit15** [comment]
used the above, still its not deleting expired sessions

**Comment by exit15** [comment]
Every day or two I delete so many sessions manually. How can it be when there are hardly 300 legit users a day?? Something is seriously wrong in this picture. Folks have no way of knowing this is happening. (I now remember past version of OC creating millions upon millions of session records in a directory which was impossible to access and very hard to delete due to its size. )
I think we need to:
1. prevent so many sessions created in the first place (bots?) ?
2. reliable delete old session records.

`[SQL] delete from `session` where `session`.expire < DATE_SUB(NOW(), INTERVAL 1 DAY);
Affected rows: 22393
Time: 1.149ms`

**Comment by danielkerr** [comment]
check yoiumdatabase and php have sync time zones

**Comment by exit15** [comment]
It is all the same (EST) I did send you snapshot of SQL and PHP and System times above (see message from December 11)

**Comment by danielkerr** [comment]
Ok will give it a test

**Comment by prometheuscz** [comment]
Hi, I have same issue. In table oc_session there was around 900 000 rows. I found that in library/session/db.php is function gc($expire), but cant find where is this function executing.

**Comment by mpimper** [comment]
> 
> 
> Hi, I have same issue. In table oc_session there was around 900 000 rows. I found that in library/session/db.php is function gc($expire), but cant find where is this function executing.
> 
> My OC version is 3.0.2.0, but checked latest 3.0.3.1 and files is same.

the same problem here. this bug must fixed as soon as possible , thanks

**Comment by gdegraaf** [comment]
What is the status of this issue? I'm still manually deleting session data every week

**Comment by exit15** [comment]
Me too, avg of 40,000 per day are being deleted. 3 sites, 120K sessions per day. Needless to say 95% of them are bots.

**Comment by boblor** [comment]
I'm just an amateur, but as far as I can see you just wrote your own Session class but you don't implement SessionHandlerInterface or call session_set_save_handler() and therefore the gc functions is never actually called... how is the gc supposed to be called ?
Did I see this wrong ?

**Comment by mhcwebdesign** [comment]
> I'm just an amateur, but as far as I can see you just wrote your own Session class but you don't implement SessionHandlerInterface or call session_set_save_handler() and therefore the gc functions is never actually called... how is the gc supposed to be called ?
> Did I see this wrong ?

You are right, the Session gc method is never called. Therefore the 'oc_session' DB table keeps on growing. This is a serious bug!

**Comment by danijelGombac** [comment]
Cache control headers not set #7008

**Comment by mhcwebdesign** [comment]
I wrote up this little vqmoid.xml script for the quick fix, it basically adds a 'DELETE FROM oc_session' for old entries (older than 1 day + gc_maxlivetime seconds).
```
<modification>
	<id>Bugfix: Session</id>
	<version>3.0.x-1.0</version>
	<vqmver>2.5.1</vqmver>
	<author>mhccorp.com</author>

	<!-- https://github.com/opencart/opencart/issues/7094 -->
	<file name="system/library/session/db.php">
		<operation>
			<search position="after"><![CDATA[$this->expire = ini_get('session.gc_maxlifetime');]]></search>
			<add><![CDATA[
		if ($this->db) {
			// remove entries older than gc_maxlifetime seconds + 1 day
			$sql = "DELETE FROM `".DB_PREFIX."session` WHERE expire < DATE_SUB(NOW(), INTERVAL ".((int)$this->expire+86400)." SECOND);";
			$this->db->query( $sql );
		}
			]]></add>
		</operation>
	</file>

</modification>
```

**Comment by gdegraaf** [comment]
tnx for this @mhcwebdesign!

**Comment by imager2019** [comment]
What would it take to make this an OCMod for 3.0.2.0??

**Comment by danielkerr** [comment]
saving the code into a text file and renaming it whatever.ocmod.zip

**Comment by MadMcJack** [comment]
Wouldn't it be better to set the expire field of the oc_session table to BIGINT and write time() + expire to that instead of a datetime? 

You then wouldn't have any problems with timezones because the timestamp is always in UTC format. 

The 'read' and 'gc' functions seem to expect a timestamp anyway. Only the 'write' function converts it to a datetime format and that seems to be causing problems.

Just my 2 cents...

**Comment by jbaop** [comment]
@MadMcJack, or use `gmdate()`.

But the point about gc() using an int timestamp while the other queries use a date string is a major oversight.

**Comment by danielkerr** [comment]
yeah it does not need to be converted to an int. it just needs the correct date time used. i will fix before the next release.

**Comment by jbaop** [comment]
@danielkerr It looks like the gc() query was fixed months ago, after this ticket was created and should be part of the 3.0.3.2 release.

I personally would separate the expiration ttls into dedicated constants instead of using PHP's config. If OC has any notion of a cron/scheduler task running in the background, the GC should probably be part of that routine.

I assume that both points could be addressed in a module/extension for those who need that type of performance enhancement.

**Comment by samaraki** [comment]
So what is the actual best solution here, seems to be about 3 different ideas?
(I've not tried any yet.)
I am using OC 3.0.3.2 and the issue still exists for me, so I'm not so sure it was fixed on this verison.
I am using BST (British Summer Time) and GMT when the clocks change back, not UTC.

**Comment by exit15** [comment]
Until today i was just deleting about 0.5 million records manually every week running a query directly on the sessions table. Today it stopped, I updated the script above to work as an ocmod. Here's what you need to do:
1. Check your sesssions db table record count before and after
2. Install using the extensions Installer
3. Perform Modifications refresh
4. 86400 sec is 24 hours, so if want you can cut it in half or more and re-archive the install.xml

[sessions_delete.ocmod.zip](https://github.com/opencart/opencart/files/3432247/sessions_delete.ocmod.zip)

**Comment by samaraki** [comment]
That didn't work for me, caused hundreds of errors and the sessions continued to grow in size, although the rows reduced.
A non-numeric value encountered in storage/modification/system/library/session/db.php on line 38

line 38 is just:
}

Although it's part of line 36 and 37.
36		} else {
37			throw new \Exception('Error: Could not load database adaptor ' . $adaptor . '!');
38		}

**Comment by exit15** [comment]
Sorry man I am using 3.0.2.0 and it works just fine. Try inserting the delete code at the top of your db.php

You want to replace this line 
`$this->expire = ini_get('session.gc_maxlifetime');`
With this
`if ($this->db) {
			$sql = "DELETE FROM `".DB_PREFIX."session` WHERE expire < DATE_SUB(NOW(), INTERVAL ".((int)$this->expire+86400)." SECOND);";
			$this->db->query( $sql );
		}`

**Comment by samaraki** [comment]
Thank you, it fixed the errors in the error log, however the sessions continue to grow in size.
See screenshot, it's not deleting them for me.
![sessions](https://user-images.githubusercontent.com/25184427/62005020-f5a9dd80-b124-11e9-9ca0-9de2ed4159fc.png)

**Comment by atnaples** [comment]
The idea "inserting the delete code at the top of your db.php" is bad, because it might increase the server response time.
I think the better solution will be to replace close() in Session with

	public function close() {
		$this->adaptor->close($this->session_id, $this->data);
	}

and add to the db.php something like this:

	public function close( $session_id, $data ) {
		$this->write($session_id, $data);
		$this->gc(ini_get('session.gc_maxlifetime'));
	}

In this case, after the session has been closed, the system will try to remove all expired one. Also, Session should not be responsible for how tyo close session.

**Comment by samaraki** [comment]
Hmmm,

There is no "close()" in my /session/db.php file.
So not sure what to replace.

![close](https://user-images.githubusercontent.com/25184427/62419296-bf181980-b674-11e9-9409-679641eab8fc.png)

**Comment by atnaples** [comment]
Yes, you are right. I said, that this method must be added to session/db.php file. See attachment

[sessions_gc.ocmod.zip](https://github.com/opencart/opencart/files/3464659/sessions_gc.ocmod.zip)

**Comment by samaraki** [comment]
Thanks,

This one seems to be working, although it does appear to be erasing the sessions entirely, not just clearing old ones like over 24 hours. And it seems to be clearing often, everytime I check the sessions they looks recently emptied.

Ideally it only wants to be clearing sessions over 24 hours old, once a day.

**Comment by samaraki** [comment]
Thank you, this worked, but it seems to be clearing everything older than 2 hours, how can I change it to make it 24 hours.

At the bottom of the file it says:
		$this->db->query("DELETE FROM `" . DB_PREFIX . "session` WHERE expire < DATE_SUB(NOW(), INTERVAL " . $expire . " SECOND);"); // + 86400

86400 is 24 hours, so not sure why its doing it at 2 hours.... Hmmm

**Comment by atnaples** [comment]
By design it's supposed to take session.gc_maxlifetime from php.ini loaded to the root of your website. I tried to use this...

**Comment by atnaples** [comment]
Helped with adding 
php_value session.gc_maxlifetime 86400
into .htaccess file

**Comment by awaro** [comment]
Данила, херли ты наших ребят не слушаешься аматор херофф?
завязывай

**Comment by atnaples** [comment]
> Данила, херли ты наших ребят не слушаешься аматор херофф?
> завязывай

5 stars

**Comment by atnaples** [comment]
> Данила, херли ты наших ребят не слушаешься аматор херофф?
> завязывай

будь осторожен, он пообещает забанить тебя, заходи ко мне, я сегодня сделал первую корзину из 2 -> 3  и она работает. site: alcher.info

**Comment by awaro** [comment]
Чего меня банить? и зачем мне корзина эта?
Ему сложно нормально начать реализовывать опенкарт что ли?
местами перетаскивает  переменные а поделу ноль, или он там диван давит а пилят такие как я что ли?
Пусть держиться одного и топит, из версии к версии тухляк сплошной.
Зато на втором третьем месте в отличии от магенто.
Конечно - ибо оно бесплатное, вот и на таком месте. сделай он это опенкарт платным уйдет оно вслед за мамонтами.

Данила, давай нормально пили уже, возьми в руки своих разрабов и впрерёд.
балячки которые ещё с 1.5х ещё таскаются от версии к версии залечи сначала потом и остальное делай.

То что тебе лет 5 10 назад говорили только ша начал внедрять.. 
такое ощущение что ты ждешь пока все забудут, т.к. не ло самого дошло.

**Comment by pbabkin** [comment]
delete from oc_session where expire < DATE_SUB(NOW(), INTERVAL 1 MONTH)
Affected 5278070 lines. (The request took 92.8493 seconds.)

who will do more? it was about 9GB into oc_session table T_T
before that I set up a scheduled task that deletes old recordings at night. stupid but it works

**Comment by straightlight** [comment]
Engwalid has recently added a session validation check that may rectify this issue. Take a look here: https://github.com/opencart/opencart/issues/7787

**Comment by danielkerr** [comment]
should be fixed in the master branch now.
