### ISSUE TITLE
Github files - PP Express Checkout

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7272]
admin/view/template/extension/payment/pp_express.twig

replace all instances of:

`%}>`

with:

`%}`

**Comment by straightlight** [comment]
In admin/controller/extension/payment/pp_express.php file,

find:

`if (isset($this->error['sandbox_signature'])) {`

add above:

if (isset($this->session->data['error_api'])) {
			$data['error_api'] = $this->session->data['error_api'];
			
			unset ($this->session->data['error_api']);
		} else {
			$data['error_api'] = '';
		}
		
		if (isset($this->session->data['error_merchant_id'])) {
			$data['error_merchant_id'] = $this->session->data['error_merchant_id'];
			
			unset ($this->session->data['error_merchant_id']);
		} else {
			$data['error_merchant_id'] = '';
		}

In admin/view/template/extension/payment/pp_express.twig file,

find:

`{% if error_warning %}`

add above:

{% if error_api %}
    <div class="alert alert-danger alert-dismissible"><i class="fa fa-exclamation-circle"></i> {{ error_api }}
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endif %}
	{% if error_merchant_id %}
    <div class="alert alert-danger alert-dismissible"><i class="fa fa-exclamation-circle"></i> {{ error_merchant_id }}
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endif %}

**Comment by straightlight** [comment]
In admin/language/en-gb/extension/payment/pp_express.php file, add at the bottom:

`$_['error_merchant_id']				 = 'The merchant ID could not be found!';`

**Comment by melvin16** [comment]
Hi straightlight,
In admin/controller/extension/payment/pp_express.php you wrote :

Then, find:

$json['error_msg'] = 'Enter a start date';

I can't find it....do you have suggestions? Thank you in advance.

**Comment by straightlight** [comment]
My bad. Thanks for mentioning this. Instructions updated on the 2nd post. Changed from $json to $response

**Comment by straightlight** [comment]
Patch released for v3.x releases: https://github.com/opencart/opencart/issues/7170

**Comment by straightlight** [comment]
Github file and all OC v3.x releases (maybe v2.x release as well): catalog/controller/extension/payment/pp_express.php file - long time reported issue:

replace:

`'recurring_name'        => (isset($product['recurring']['recurring_name']) ? $product['recurring']['recurring_name'] : ''),`

with:

`'recurring_name'        => (isset($product['recurring']['name']) ? $product['recurring']['name'] : ''),`

This should resolved the recurring name issue but also needs to be added into the catalog/view/theme/default/template/extension/payment/pp_express_confirm.twig file.

**Comment by aj1322001** [comment]
upon confirming order, 

Notice: Undefined index: affiliate_id in /home4/mywebsite.com/catalog/controller/extension/payment/pp_express.php on line 1214Warning: Cannot modify header information - headers already sent by (output started at /home4/mywebsite.com/catalog/controller/startup/error.php:34) in /home4/storage/modification/system/library/response.php on line 36

**Comment by straightlight** [comment]
I question the ways of the array validations on this platform as only validating the variable itself seems to be insufficient to avoid an error in this case.

See if the following makes a difference. In catalog/controller/extension/payment/pp_express.php, find:

`if ($affiliate_info) {`

replace with:

`if (!empty($affiliate_info['affiliate_id']) && !empty($affiliate_info['commission'])) {`

Then, retry a new order with an affiliate tracking number.

**Comment by straightlight** [comment]
File attachment replaced on topic. Also fixed the marketing_info validation.

**Comment by amshehzad** [comment]
@straightlight I have applied the patch you provided and clear the cache before reinstalling but still getting the same error :
"Error: There was an error fetching the PayPal token at eval (eval at globalEval "
![image](https://user-images.githubusercontent.com/15146578/57195830-7915c180-6f70-11e9-867f-e9d812e00e5c.png)
can you please tell me what's wrong here ?

**Comment by straightlight** [comment]
As much and the same usual response from the OC forum users trying this fix, you are using Journal3. See from a fresh installation of OC (v3.0.3.2) by, then, installing the PP Express Fix package if it will work. Also take note that the IPN / Callback URL may need to be changed via your test environment location rather than your live server.

I would also suggest to set your live store under maintenance, especially if the screenshot above originates from the live store until you complete these steps with PP Express Checkout.

**Comment by amshehzad** [comment]
Thank you so much for your suggestion, I have just enabled the errors for testing, I have installed the fix packages you provided but still the same error, I would really very glad if you can help on this as I'm trying to fix it from last two days

**Comment by straightlight** [comment]
If it indicates the exact same error as your above screenshot, it means you are still using Journal which is not supported which this fix solution. The main idea was to propose this fix for the core by using a fresh installation due to geographic restrictions that could not be identified out-of-the-box. Most of the users wants to remain with Journal and that is under their responsibility to use a 3rd party extension to sell their products and services with OC.

With that being said, once a fresh installation will be done, see the results. In addition, this section is not for troubleshooting, it is for reporting technical issues 'from the core' and NOT from 3rd party extensions. To report 3rd party extension issues, please report them on the official topic on the Opencart forum.

**Comment by straightlight** [comment]
Official topic: https://forum.opencart.com/viewtopic.php?f=201&t=210578

**Comment by straightlight** [comment]
Issue resolved on my Github namespace for: catalog/controller/extension/payment/pp_express.php file in the checkout() method. pp_express.twig file uses application/json-token while the checkout() method in the controller was also handling a failed redirection with $this->response->redirect since the setOutput was set to JSON encoding.

Balanced both IF statements for non-JSON and JSON conditions to handle successful redirection with $this->session->data and JSON encoding. Tested with a user on a custom job having a PayPal Business Account, mentions she no longer since the PayPal token error message as it continues to the next steps accordinly.

**Comment by tomtheone** [comment]
Hmmm...
I still have this error after replacing pp_express.php

Error: Error: There was an error fetching the PayPal token at eval (eval at globalEval (http://shop.roganmedical.ch/catalog/view/javascript/jquery/jquery-2.1.1.min.js:2:2536), :22:21) at _loop (https://www.paypalobjects.com/api/checkout.js:779:46) at ZalgoPromise._proto.dispatch (https://www.paypalobjects.com/api/checkout.js:796:53) at ZalgoPromise._proto.resolve (https://www.paypalobjects.com/api/checkout.js:751:66) at https://www.paypalobjects.com/api/checkout.js:737:41 at XMLHttpRequest. (https://www.paypalobjects.com/api/checkout.js:1092:24) at Object._RECEIVE_MESSAGE_TYPE. [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:4247:27) at receiveMessage (https://www.paypalobjects.com/api/checkout.js:4278:48) at messageListener (https://www.paypalobjects.com/api/checkout.js:4297:9)

Any idea?

**Comment by straightlight** [comment]
Journal?

**Comment by tomtheone** [comment]
I would like to help/assist but i try to avoid to blame myself to mutch. What do you need/mean by journal?

**Comment by straightlight** [comment]
Are you using the Journal theme? If not, ensure the debug mode is enabled and set your site under maintenance. Then, please provide the debug log entries.

**Comment by tomtheone** [comment]
No, not using a theme called Journal. Everything default, out of the box. Ok, i go to find out how to enable debug mode for opencart, etc.

**Comment by tomtheone** [comment]
I found the root cause: It's working without the patch provided in the github repo.

Error log is:
"L_SHORTMESSAGE0":"Shipping Address Postal Code Empty","L_LONGMESSAGE0":"The field Shipping Address Postal Code is required",

I did not fill out the Post Code field.

Info: Regardless of the red asterisk next to the form-field for the ZIP code, you can proceed with the order. The form-field is not checked by opencart and you can proceed without having value added.

**Comment by tomtheone** [comment]
Btw: I have Google reCaptcha enabled - i saw that it's also possible to perform a checkout/payment without doing the captcha verification; just not doing/verifying it and proceed; works fine.

**Comment by bluebirdppc** [comment]
Received this error:

[22-Aug-2019 02:44:54 UTC] PHP Parse error:  syntax error, unexpected 'if' (T_IF) in /home/c6me85pv0szy/public_html/catalog/model/localisation/geo_zone.php on line 44

OC Version 3.0.3.2

**Comment by straightlight** [comment]
Fixed. Thanks. However, this has nothing to do with PayPal Express for this error above.

**Comment by bluebirdppc** [comment]
Thank you. but there is a new error:

[23-Aug-2019 01:29:52 UTC] PHP Parse error:  syntax error, unexpected 'if' (T_IF) in /home/c6me85pv0szy/public_html/catalog/model/localisation/geo_zone.php on line 34

**Comment by straightlight** [comment]
Fixed, thanks.

**Comment by bluebirdppc** [comment]
Have you updated the code?

**Comment by bluebirdppc** [comment]
the error still exists:

[27-Aug-2019 02:59:50 UTC] PHP Parse error:  syntax error, unexpected 'if' (T_IF) in /home/c6me85pv0szy/public_html/catalog/model/localisation/geo_zone.php on line 45

**Comment by engwalid1971** [comment]
- **Replace:**
`if ($this->config->get('payment_' . $result['code'] . '_status') && $this->config->get('payment_' . $result['code'] . '_status') {`
**With:**
`if ($this->config->get('payment_' . $result['code'] . '_status')) {`

- **Replace:**
`if (!empty($this->config->get('shipping_' . $result['code'] . '_status') && $this->config->get('shipping_' . $result['code'] . '_status') {`
**With:**
`if ($this->config->get('shipping_' . $result['code'] . '_status')) {`

- **Replace:**
`if (!empty($this->config->get('shipping_' . $result['code'] . '_location') && $location == $this->config->get('shipping_' . $result['code'] . '_location') && $this->config->get('shipping_' . $result['code'] . '_location') == 'address') {`
**With:**
`if (!empty($this->config->get('shipping_' . $result['code'] . '_location')) && $location == $this->config->get('shipping_' . $result['code'] . '_location') && $this->config->get('shipping_' . $result['code'] . '_location') == 'address') {`
**Or:**
`if ($this->config->get('shipping_' . $result['code'] . '_location') && $location == $this->config->get('shipping_' . $result['code'] . '_location') && $this->config->get('shipping_' . $result['code'] . '_location') == 'address') {`

**Comment by bluebirdppc** [comment]
@straightlight Thank you. I replaced all code you mentioned above, but received new error.

[27-Aug-2019 08:30:02 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ModelExtensionTotalSubTotal::getTotal(), 0 passed in /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader.php on line 248 and exactly 1 expected in /home/c6me85pv0szy/public_html/catalog/model/extension/total/sub_total.php:3
Stack trace:
#0 /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader.php(248): ModelExtensionTotalSubTotal->getTotal()
#1 /home/c6me85pv0szy/public_html/catalog/model/localisation/geo_zone.php(32): Loader->{closure}(Array, Array, 0)
#2 /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader.php(248): ModelLocalisationGeoZone->getZoneToGeoZoneLocation('account')
#3 /home/c6me85pv0szy/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array)
#4 /home/c6me85pv0szy/public_html/catalog/model/account/custom_field.php(34): Proxy->__call('getZoneToGeoZon...', Array)
#5 /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader in /home/c6me85pv0szy/public_html/catalog/model/extension/total/sub_total.php on line 3
[27-Aug-2019 08:30:04 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ModelExtensionTotalSubTotal::getTotal(), 0 passed in /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader.php on line 248 and exactly 1 expected in /home/c6me85pv0szy/public_html/catalog/model/extension/total/sub_total.php:3
Stack trace:
#0 /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader.php(248): ModelExtensionTotalSubTotal->getTotal()
#1 /home/c6me85pv0szy/public_html/catalog/model/localisation/geo_zone.php(32): Loader->{closure}(Array, Array, 0)
#2 /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader.php(248): ModelLocalisationGeoZone->getZoneToGeoZoneLocation('account')
#3 /home/c6me85pv0szy/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array)
#4 /home/c6me85pv0szy/public_html/catalog/model/account/custom_field.php(34): Proxy->__call('getZoneToGeoZon...', Array)
#5 /home/c6me85pv0szy/public_html/system/storage/modification/system/engine/loader in /home/c6me85pv0szy/public_html/catalog/model/extension/total/sub_total.php on line 3
