### ISSUE TITLE
Session problems in any async (concurrent) requests that set / change something in session

### ISSUE THREAD

**Issue by ciotuvasile** [opencart/opencart#7968]
**What version of OpenCart are you reporting this for?**
All 3.x versions 

**Describe the bug**
If you have a javascript which is calling 2 opencart routes and both add something in session then the request who end last one will overwrite session data without being aware of what first request tried to add in session.   

**To Reproduce**
Controller: test/test
`public function f1() {
   $this->session->data['f1'] = '1';
}

public function f2() {
   $this->session->data['f2'] = '2';
}

// javascript
function doF1() {
   $.ajax('{
      url: 'index.php?route=test/test/f1'
   }');
}

function doF2() {
   $.ajax('{
      url: 'index.php?route=test/test/f2'
   }');
}`

**Explanation:**
![session-explanation](https://user-images.githubusercontent.com/252103/83256935-1109cd00-a1bc-11ea-982b-e185cdc434a2.jpg)

Because in 3.x is used DB or file for session storage and session data is saved on script end (via register_shutdown_function(array($this, 'close')))

**Expected behavior**
See last section from image
Forcing with async: false will slow down things that are supposed to run fast.

**Additional context**
Why OC 2.3.x and older version don't have this problem?
Because is used native session by default and this kind of problems are avoided.
$this->data = &$_SESSION[$this->session_id];

**Comment by danielkerr** [comment]
i fixed this by chaining ajax requests in the checkout. did u add another extension that uses ajax?

**Comment by danielkerr** [comment]
need to blog the system creating new sessions from jquery load

**Comment by ciotuvasile** [comment]
Thank you for your answer.

I've discovered that a lot of extensions (from other developers) had same problem and developers developers had no idea what's wrong. (most of them checkout extensions)
In my case was possible to call controllers before calling async functions and i've solved problem.
We provided for our customers (as optional files) modified versions of session class (one based on php native and other based on redis)

Maybe in the future, native php session should still be available as option. 
In this way, if there's some big store which use distributed system then they can use activated DB option and small store PHP Native.
Small stores usually have cheap hosting services and keeping session in DB i saw is introducing some delay compared to php native. (even in some average hosting services)
I know why you decided to go with DB :)

default Redis class from OC3.x has also some bugs but i'll explain on other topic when i'll find some time.
Opecart + Redis = heaven :) but found that not too many of store owners know about this (even when some of them already have redis installed on server)
. 
I HOPE OpenCart will be soon the no 1 shopping cart platform

**Comment by WebkulOpencart** [comment]
this issue is already resolved in version 3.0.3.6
https://prnt.sc/wliksn

**Comment by ADDCreative** [comment]
@WebkulOpencart I don't think you've tested correctly. I've just tested 3.0.3.7 and still see the issue.

Also looks like someone else has reported an issue https://github.com/opencart/opencart/issues/9630, which is probably cause by this.

**Comment by WebkulOpencart** [comment]
@ADDCreative Please share some video of the test case so that we can check

**Comment by nethubdesign** [comment]
Hi all,

Yes, we reported issue as we didn't find this thread. We confirmed the exact same problem even current release 3.0.3.7  . You may take a look on our report #9630 too.

We also recorded a video, please take a look: [https://www.youtube.com/watch?v=yBlFnuHXkMY](url)
