### ISSUE TITLE
JSON error popup on checkout->confirm

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8021]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre 
([June 19, 2020 - 7:51am - (EST Time) - Update]: Fixed numerous files in core and features.)
**Describe the bug**
because of 2 issues:
**1. Illegal string offset 'config_logo' in catalog/controller/mail/order.php on line 96**
no wonder, since `model_setting_setting->getValue` already returns a the plain value, and not an array of values.
So, I got it fixed like that

```
`$config_logo = $this->model_setting_setting->getValue('config_logo', $order_info['store_id']);
		
if ($config_logo) {
			if (is_file(DIR_IMAGE . html_entity_decode($config_logo, ENT_QUOTES, 'UTF-8'))) {
				$data['logo'] = $this->model_tool_image->resize(DIR_IMAGE . html_entity_decode($config_logo, ENT_QUOTES, 'UTF-8'), $this->config->get('theme_default_image_location_width'), $this->config->get('theme_default_image_cart_height'));
			}
`
```
**2. Undefined index: email in catalog/controller/mail/order.php on line 486**
no idea which way email is expected to be retrieved, all I can tell is that my $this->request->post array is completely empty

**Comment by straightlight** [comment]
Fixed for the logo. However, more info is needed for line 486.

**Comment by straightlight** [comment]
Fixed. Compared with master branch. The setReplyTo method from the email in the alert() method has been removed. Therefore, this commit will now be closed.

**Comment by githubertus** [comment]
still not working, now I'm getting
**Call to a member function resize() on null in catalog/controller/mail/order.php:96**
fixed with
```
if ($config_info && is_file(DIR_IMAGE . html_entity_decode($config_info, ENT_QUOTES, 'UTF-8'))) {
	$this->load->model('tool/image');
	.....

```
sorry, overlooked that

**Comment by straightlight** [comment]
Fixed.
