### ISSUE TITLE
[OC master branch] Improve name spaces

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#8283]
At the moment, the master branch uses something like this for the namespaces, as e.g. shown below for the **admin/controller/common/dashboard.php**:

```
<?php
namespace Application\Controller\Common;
class Dashboard extends \System\Engine\Controller {
....
```

I think it would be more consistent to use something like this instead:

```
<?php
namespace Opencart\Admin\Controller\Common;
class Dashboard extends \Opencart\System\Engine\Controller {
....
```

This would be in line with namespace conventions used in other packages like Twig, Symfony, etc where their namespaces start with **Twig\\** or **Symfony\\** etc.

So for OpenCart, name spaces typcially would start with **Opencart\\Admin\\** , **Opencart\\Catalog\\**,  **Opencart\\System\\** etc.

**Comment by straightlight** [comment]
There are most of Github repositories that builds their projects starting with Application. It is simply a more opted convention on Github in general.

**Comment by danielkerr** [comment]
is there a way so i can use

namespace Opencart\Admin\Controller\Common;

or 

namespace Opencart\Catalog\Controller\Common;

the issue is that the loader class needs needs the same path to be used. it would be good if i could do 

use \Opencart\Catalog\Controller as Application;

**Comment by danielkerr** [comment]
updating namspaces now.

**Comment by mhcwebdesign** [comment]
I'll try it out. I am not quite sure what you mean by 

"but seems u can not use it like this if you are using a the class name as a string"

**Comment by danielkerr** [comment]
@mhcwebdesign 

I mean  you can't do:

use \Opencart\Catalog\Controller as Controller;

$class = 'Controller\Catalog\Product';

it has to be

$class = '\Opencart\Catalog\Controller\Catalog\Product';

**Comment by mhcwebdesign** [comment]
@Daniel: I ran some tests, and noticed the following needs to be fixed for making your suggestion work on Linux:

File '**system/engine/framework.php**' doesn't need a second instantiation of the '**Opencart\System\Engine\Autoloader**' which won't work anyway. The Autoloader is already instantiated in the 'index.php' files!

Also, in the '**system/engine/autoloader.php**' make sure all back-slashes are replaced with forward-slashes for the file names. 

Replace the line
`$file = $this->data[$namespace] . strtolower(preg_replace('~([a-z])([A-Z]|[0-9])~', '\\1_\\2', substr($class, strlen($namespace)))) . '.php';
`

with this line:
`$file = $this->data[$namespace] . str_replace('\\','/',strtolower(preg_replace('~([a-z])([A-Z]|[0-9])~', '\\1_\\2', substr($class, strlen($namespace)+1)))) . '.php';
`

**Comment by mhcwebdesign** [comment]
Also, file '**system/library/mail.php**' needs to use the correct namespace for the $class variable.

Replace
`$class = 'Mail\\' . $adaptor;
`

With this line:
`$class = 'Opencart\\System\\Library\\Mail\\' . $adaptor;`

**Comment by mhcwebdesign** [comment]
I can see you did some improvements to the namespaces now.

However, you are still using the '\Application' in the namespace instead of the suggested '\System', '\Admin', or '\Catalog'. I think a simple change can easily accomplish this:

In file 'system/config/admin.php', add this:
```
// Application
$_['application']       = 'Admin';

```

In file 'system/config/catalog.php' add this:
```
// Application
$_['application']       = 'Catalog';

```

In file 'system/config/install.php' add this:
```
// Application
$_['application']       = 'Install';

```

Then the **system/framework.php** will automatically load the 'application' setting into the respective config. From there copy it to the registry, e.g. with this in the **system/framework.php**:

```
	......
	// Load the default config
	$config->load('default');
	$config->load($application);
	$registry->set('config', $config);

	// Application
	$registry->set('application',$config->get('application'));
	......

```

Now we can use the 'application' in the **system/action.php**:

```
	.....
	public function __construct(string $route) {
		$this->route = preg_replace('/[^a-zA-Z0-9_\/]/', '', $route);
	}
	.....
	public function execute(Registry $registry, array &$args = []) {
		$route = $this->getId();
		$application = $registry->get('application');
		$class = 'Opencart\\'.$application.'\\Controller\\' . str_replace(['_', '/'], ['', '\\'], ucwords($route, '_/'));

		if (class_exists($class)) {
			$this->class = $class;
		} else {
			$this->class = substr($class, 0, strrpos($class, '\\'));
			$this->method = substr($route, strrpos($route, '/') + 1);
		}

		// Stop any magical methods being called
		if (substr($this->method, 0, 2) == '__') {
			return new \Exception('Error: Calls to magic methods are not allowed!');
		}

		// Initialize the class
		$controller = new $this->class($registry);

		$callable = [$controller, $this->method];

		if (is_callable($callable)) {
			return call_user_func_array($callable, $args);
		} else {
			return new \Exception('Error: Could not call ' . $this->route . '!');
		}
	}
	.....
```

Above changes allow us to use namespaces such as 'Opencart\Admin\Controller\Common', 'Opencart\Catalog\Controller\Common' etc instead of the 'Opencart\Application\Controller\Common'.

**Comment by danielkerr** [comment]
maybe better to have the action call from web root.

**Comment by danielkerr** [comment]
@mhcwebdesign  I think ur solution is correct

**Comment by danielkerr** [comment]
ok this is working now.

**Comment by mhcwebdesign** [comment]
Great! I'll test it all when I have some time.

**Comment by mhcwebdesign** [comment]
It's not working for the install, see #9375 

The install never calls the response->setOutput hence resulting in this error:

Error: Typed property Opencart\System\Library\Response::$output must not be accessed before initialization in /home/juergen/htdocs/opencart-4-0-0-0-b-20210227/system/library/response.php on line 117

**Comment by mhcwebdesign** [comment]
2 simple fixes should resolve the issue with the install:

1)
In the folders **install/controller** and **install/model** , for all their PHP files, change the old

`namespace Opencart\Application\Model\Install;`

to

`namespace Opencart\Install\Model\Install;`


2)
Please be aware that the file system on Linux, unlike Windows NTFS, is case sensitive. E.g. Linux won't be able to load file '/system/config/Install.php', because the actual file uses lowercase letters in its filename. Therefore, use this function in 'system/engine/config.php':

```
	public function load(string $filename): array {
		$file = $this->directory . $filename . '.php';

		$namespace = '';

		$parts = explode('/', $filename);

		foreach ($parts as $part) {
			if (!$namespace) {
				$namespace .= $part;
			} else {
				$namespace .= '/' . $part;
			}

			if (isset($this->path[$namespace])) {
				$file = $this->path[$namespace] . substr($filename, strlen($namespace)) . '.php';
			}
		}

		// make sure to use lowercase for the file basename
		$file = dirname($file).'/'.strtolower(basename($file));

		if (is_file($file)) {
			$_ = [];

			require($file);

			$this->data = array_merge($this->data, $_);

			return $this->data;
		} else {
			return [];
		}
	}
```

Above mentioned changes should resolve the install issue, though I have to do some more testing.

**Comment by exelaguilar** [comment]
@mhcwebdesign, this fixed the loading issue but I was still getting a **The page you requested cannot be found!** when trying to load the install.

I noticed the install.php had <? and the config.php has <?php, I replaced <? with <?php on the install.php and got the actual install to load. 

It wasn't loading that install.php correctly.

https://imgur.com/a/0QOt1fW

**Comment by exelaguilar** [comment]
I was also getting an error at step 3 of the installation, I was getting redirected to /install/error.html with no reason why.

I edited the install.php config 

`$_['error_display']     = true;`

Which finally didn't just redirect to a random missing page, but:

`TypeError: Cannot assign string to property Opencart\System\Library\DB\MySQLi::$connection of type object in /Users/exel/Sites/localhost/exel/system/library/db/mysqli.php on line 86`


**system/library/db/mysqli.php**

Line 86, comment it out:

`//$this->connection = '';`

**Comment by danielkerr** [comment]
closing this. i have updated the system. its working. im updating to the latest php8 coding style using types.

**Comment by kktsvetkov** [comment]
> I mean you can't do:
>
> use \Opencart\Catalog\Controller as Controller;
> 
> $class = 'Controller\Catalog\Product';
> 
> it has to be
> 
> $class = '\Opencart\Catalog\Controller\Catalog\Product';

I think you can just do this instead:
```php 
use \Opencart\Catalog\Controller as Controller;
$class = Controller\Catalog\Product::class;
```
PHP itself will resolve the full classname and then if you print it, you will see that it is actually `\Opencart\Catalog\Controller\Catalog\Product`
